version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starter-kit-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: starter_kit
      DB_USERNAME: root
      DB_PASSWORD: rootpw
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  web:
    image: phpmyadmin
    container_name: starter-kit-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: starter-kit-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: starter_kit
      MYSQL_USER: starter_kit
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    container_name: starter-kit-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db-data:
